INHERIT: ../../../shared/base.yml
site_name: MemberExport documentation
site_url: https://docs.soetemansoftware.nl/memberexport/latest/
nav:
  - Home: index.md
  - Installation: installation.md
  - Export members: export.md
  - Configuration: configuration.md
  - Extend MemberExport: extending.md
  - Troubleshooting: troubleshooting.md
