INHERIT: ../../../shared/base.yml
site_name: MediaProtect documentation
site_url: https://docs.soetemansoftware.nl/mediaprotect/17/
nav:
  - Home: index.md
  - Installation: installation.md
  - Protect media: protect-media.md
  - Dashboards: dashboards.md
  - Configuration: configuration.md
  - Developers:
      - Library: developers/library.md
      - Notifications: developers/notifications.md
  - Troubleshooting: troubleshooting.md
